-- 001 init — 回滚脚本（逆序删除）
DROP INDEX IF EXISTS ix_audit_created;
DROP INDEX IF EXISTS ix_audit_entity;
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS settings;
DROP INDEX IF EXISTS ix_compile_runs_conversation;
DROP TABLE IF EXISTS compile_runs;
DROP TABLE IF EXISTS knowledge_links;
DROP TABLE IF EXISTS relations;
DROP TABLE IF EXISTS entities;
DROP INDEX IF EXISTS ix_ksources_message;
DROP INDEX IF EXISTS ix_ksources_knowledge;
DROP TABLE IF EXISTS knowledge_sources;
DROP INDEX IF EXISTS ix_knowledge_slug;
DROP INDEX IF EXISTS ix_knowledge_status;
DROP TABLE IF EXISTS knowledge;
DROP INDEX IF EXISTS ix_jobs_next_run;
DROP INDEX IF EXISTS ix_jobs_status;
DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS sync_runs;
DROP INDEX IF EXISTS ix_messages_hash;
DROP INDEX IF EXISTS ix_messages_conversation;
DROP TABLE IF EXISTS messages;
DROP INDEX IF EXISTS ix_conversations_updated;
DROP INDEX IF EXISTS ix_conversations_provider;
DROP TABLE IF EXISTS conversations;
DROP TABLE IF EXISTS providers;
-- schema_migrations 由迁移运行器自行维护，不在此删除（否则回滚无法记录进度）。
