-- 002 fts — 回滚脚本
DROP TRIGGER IF EXISTS knowledge_fts_au;
DROP TRIGGER IF EXISTS knowledge_fts_ad;
DROP TRIGGER IF EXISTS knowledge_fts_ai;
DROP TRIGGER IF EXISTS messages_fts_au;
DROP TRIGGER IF EXISTS messages_fts_ad;
DROP TRIGGER IF EXISTS messages_fts_ai;
DROP TABLE IF EXISTS knowledge_fts;
DROP TABLE IF EXISTS messages_fts;
